# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - "main"
      - "pipeline"
  pull_request:
    branches:
      - "main"

env:
  GENERATE_DEPS: "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 google.golang.org/grpc/cmd/protoc-gen-go-grpc google.golang.org/protobuf/cmd/protoc-gen-go"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler
          version: 1.0
          
      - name: Install dependencies
        run: |
          (cd racing && go install ${GENERATE_DEPS})
          (cd api && go install ${GENERATE_DEPS})

      - name: Build
        run: |
          (cd racing && go generate ./... && go build)
          (cd api && go generate ./... && go build)

      #- name: Test
      #  run: go test -v ./...